
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Programmer PC
 */
public class edit_voucher extends javax.swing.JFrame {

    /**
     * Creates new form edit_voucher
     */
    private PreparedStatement pst;
    private Connection conn;
    private ResultSet rs;
    private DefaultTableModel model,mod;
    private String voucher;
    public edit_voucher() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        conn=Database.Connect();
        model=(DefaultTableModel) open_voucher.getModel();
        mod=(DefaultTableModel) all_voucher.getModel();
        set_value();
        sub_total.setEditable(false);
        total_tax.setEditable(false);
        net_amount.setEditable(false);
        ADD.setEnabled(false);
        EDIT.setEnabled(false);
        DELETE.setEnabled(false);
        try {
            this.setIconImage(ImageIO.read(new File("C:\\Program Files (x86)\\S K Enterprise\\Software\\Shop\\Sk Shop Software\\icon.JPG")));
        } catch (IOException ex) {
            Logger.getLogger(edit_voucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void set_value(){
        String sql="select * from voucher";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            mod.setRowCount(0);
            while(rs.next()){
                mod.addRow(new Object[] {rs.getString("name"),rs.getString("net_amount"),rs.getString("voucher_number")});
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        all_voucher.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        all_voucher = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customer = new javax.swing.JTextField();
        date = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        open_voucher = new javax.swing.JTable();
        EDIT = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        OPEN = new javax.swing.JButton();
        ADD = new javax.swing.JButton();
        REMOVE = new javax.swing.JButton();
        CALCULATE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        voucher_number = new javax.swing.JTextField();
        REFRESH = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sub_total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        total_tax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        net_amount = new javax.swing.JTextField();
        CALCULATE1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        all_voucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Amount", "Voucher Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(all_voucher);
        if (all_voucher.getColumnModel().getColumnCount() > 0) {
            all_voucher.getColumnModel().getColumn(0).setResizable(false);
            all_voucher.getColumnModel().getColumn(0).setPreferredWidth(190);
            all_voucher.getColumnModel().getColumn(1).setResizable(false);
            all_voucher.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Edit Voucher");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Customer Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Date Of Voucher");

        try {
            date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        open_voucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No.", "Item Name", "Rate", "GST", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(open_voucher);
        if (open_voucher.getColumnModel().getColumnCount() > 0) {
            open_voucher.getColumnModel().getColumn(0).setResizable(false);
            open_voucher.getColumnModel().getColumn(1).setResizable(false);
            open_voucher.getColumnModel().getColumn(1).setPreferredWidth(200);
            open_voucher.getColumnModel().getColumn(2).setResizable(false);
            open_voucher.getColumnModel().getColumn(3).setResizable(false);
            open_voucher.getColumnModel().getColumn(4).setResizable(false);
            open_voucher.getColumnModel().getColumn(5).setResizable(false);
        }

        EDIT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EDIT.setText("Edit");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        DELETE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DELETE.setText("Delete");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        OPEN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OPEN.setText("Open");
        OPEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPENActionPerformed(evt);
            }
        });

        ADD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ADD.setText("Add");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        REMOVE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        REMOVE.setText("Remove");
        REMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEActionPerformed(evt);
            }
        });

        CALCULATE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CALCULATE.setText("Calculate");
        CALCULATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULATEActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Enter Voucher Number");

        REFRESH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        REFRESH.setText("Refresh");
        REFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESHActionPerformed(evt);
            }
        });

        SEARCH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SEARCH.setText("Search");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel8.setText("Sub Total");

        sub_total.setBackground(new java.awt.Color(102, 102, 0));
        sub_total.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        sub_total.setForeground(new java.awt.Color(255, 255, 0));
        sub_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sub_total.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel9.setText("Total Tax");

        total_tax.setBackground(new java.awt.Color(102, 102, 0));
        total_tax.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        total_tax.setForeground(new java.awt.Color(255, 255, 0));
        total_tax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_tax.setText("0.00");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel7.setText("Net Amount");

        net_amount.setBackground(new java.awt.Color(102, 102, 0));
        net_amount.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        net_amount.setForeground(new java.awt.Color(255, 255, 0));
        net_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        net_amount.setText("0.00");

        CALCULATE1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CALCULATE1.setText("Clear");
        CALCULATE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULATE1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(REMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(CALCULATE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(CALCULATE1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(net_amount)))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(OPEN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(REFRESH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(voucher_number, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(voucher_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEARCH))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EDIT)
                    .addComponent(OPEN)
                    .addComponent(DELETE)
                    .addComponent(REFRESH))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADD)
                    .addComponent(REMOVE)
                    .addComponent(CALCULATE)
                    .addComponent(CALCULATE1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
        String sql="select * from voucher where voucher_number='"+voucher_number.getText()+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            mod.setRowCount(0);
            while(rs.next()){
                mod.addRow(new Object[] {rs.getString("name"),rs.getString("net_amount"),rs.getString("voucher_number")});
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        all_voucher.setModel(mod);
    }//GEN-LAST:event_SEARCHActionPerformed

    private void REFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESHActionPerformed
        // TODO add your handling code here:
        set_value();
    }//GEN-LAST:event_REFRESHActionPerformed

    private void OPENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPENActionPerformed
        // TODO add your handling code here:
        if(all_voucher.getSelectedRow()==-1)
            JOptionPane.showMessageDialog(null, "No Row Selected");
        else{
            String sql="select * from voucher where voucher_number='"+all_voucher.getValueAt(all_voucher.getSelectedRow(), 2)+"'";
            String SQL="select * from voucher_contents where voucher_number='"+all_voucher.getValueAt(all_voucher.getSelectedRow(), 2)+"'";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                model.setRowCount(0);
                if(rs.next()){
                    customer.setText(rs.getString("name"));
                    date.setText(rs.getString("date"));
                    sub_total.setText(rs.getString("sub_total"));
                    total_tax.setText(rs.getString("total_tax"));
                    net_amount.setText(rs.getString("net_amount"));
                    pst=conn.prepareStatement(SQL);
                    voucher=rs.getString("voucher_number");
                    rs=pst.executeQuery();
                    while(rs.next()){
                        model.addRow(new Object[] {rs.getString("sl_no"),rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),
                        rs.getString("qty"),rs.getString("total")});
                    }
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
            ADD.setEnabled(true);
            EDIT.setEnabled(true);
            DELETE.setEnabled(true);
        }
    }//GEN-LAST:event_OPENActionPerformed

    private void REMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modd=(DefaultTableModel) open_voucher.getModel();
        modd.removeRow(open_voucher.getSelectedRow());
        open_voucher.setModel(modd);
    }//GEN-LAST:event_REMOVEActionPerformed

    private void CALCULATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULATEActionPerformed
        // TODO add your handling code here:
        double sub=0.00,tax=0.00,nett=0.00;
        for(int i=0;i<open_voucher.getRowCount();i++){
            sub+=Double.parseDouble(open_voucher.getValueAt(i, 2).toString());
            tax+=Double.parseDouble(open_voucher.getValueAt(i, 3).toString());
            nett+=Double.parseDouble(open_voucher.getValueAt(i, 5).toString());
        }
        sub_total.setText(""+sub);
        total_tax.setText(""+tax);
        net_amount.setText(""+nett);
    }//GEN-LAST:event_CALCULATEActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
        String item=JOptionPane.showInputDialog("Enter Item Name");
        if(item.equals(""))
            JOptionPane.showMessageDialog(null, "Enter A Valid Item");
        else{
            String sql="select * from product where item_name='"+item+"'";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    String x=JOptionPane.showInputDialog("Enter Quantity");
                    double y=Double.parseDouble(rs.getString("Total_MRP"))*Double.parseDouble(x);
                    int a=(Integer.parseInt(open_voucher.getValueAt(open_voucher.getRowCount()-1, 0).toString())+1);
                    model.addRow(new Object[] {""+a,rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),x,y});
                }
                else
                    JOptionPane.showMessageDialog(null, "No Such Item Found");
            }catch(Exception ex){
                ex.printStackTrace();
            }
            open_voucher.setModel(model);
        }
    }//GEN-LAST:event_ADDActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        String sql="delete from voucher where voucher_number='"+all_voucher.getValueAt(all_voucher.getSelectedRow(), 2)+"'";
        String SQL="delete from voucher_contents where voucher_number='"+all_voucher.getValueAt(all_voucher.getSelectedRow(), 2)+"'";
        try{
            pst=conn.prepareStatement(sql);
            pst.execute();
            pst=conn.prepareStatement(SQL);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted Sucessfully");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_DELETEActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        // TODO add your handling code here:
        String sql="UPDATE voucher SET name='"+customer.getText()+"',date='"+date.getText()+"',sub_total='"+sub_total.getText()+"',total_tax='"
                +total_tax.getText()+"',net_amount='"+net_amount.getText()+"' WHERE voucher_number='"+voucher+"'";
        String Sql="delete from voucher_contents where voucher_number='"+voucher+"'";
        try{
            pst=conn.prepareStatement(sql);
            pst.execute();
            pst=conn.prepareStatement(Sql);
            pst.execute();
            for(int i=0;i<open_voucher.getRowCount();i++){
                String SQL="INSERT INTO voucher_contents(voucher_number, sl_no, item_name, rate, GST, qty, total) "
                    +"VALUES ('"+voucher+"','"+open_voucher.getValueAt(i, 0)+"','"+open_voucher.getValueAt(i, 1)+"','"
                        +open_voucher.getValueAt(i, 2)+"','"+open_voucher.getValueAt(i, 3)+"','"+open_voucher.getValueAt(i, 4)+"','"
                        +open_voucher.getValueAt(i, 5)+"')";
                pst=conn.prepareStatement(SQL);
                pst.execute();
            }
            JOptionPane.showMessageDialog(null, "Voucher Updated Sucessfully");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_EDITActionPerformed

    private void CALCULATE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULATE1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel) open_voucher.getModel();
        m.setRowCount(0);
        open_voucher.setModel(m);
    }//GEN-LAST:event_CALCULATE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_voucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton CALCULATE;
    private javax.swing.JButton CALCULATE1;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton OPEN;
    private javax.swing.JButton REFRESH;
    private javax.swing.JButton REMOVE;
    private javax.swing.JButton SEARCH;
    private javax.swing.JTable all_voucher;
    private javax.swing.JTextField customer;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField net_amount;
    private javax.swing.JTable open_voucher;
    private javax.swing.JTextField sub_total;
    private javax.swing.JTextField total_tax;
    private javax.swing.JTextField voucher_number;
    // End of variables declaration//GEN-END:variables
}
