
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Programmer PC
 */
public class estimate extends javax.swing.JPanel {

    /**
     * Creates new form estimate
     */
    private PreparedStatement pst;
    private ResultSet rs;
    private Connection conn;
    private DefaultTableModel model;
    public estimate() {
        initComponents();
        conn=Database.Connect();
        model=(DefaultTableModel) tab.getModel();
        set_value();
        set_button();
        set_date();
        set_estimate();
    }
    private void set_estimate(){
        estimate_no.setText(new Random().nextInt(999)+new Random().nextInt(888)+"");
    }
    private void set_date(){
        date.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
    }
    private void set_button(){
        ADD_.setEnabled(false);
        REMOVE_.setEnabled(false);
        CLEAR_.setEnabled(false);
        SAVE_.setEnabled(false);
        CALCULATE_.setEnabled(false);
        OPEN_.setEnabled(false);
    }
    private void set_value(){
        String sql="select * from customer";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                cus_name.addItem(rs.getString("cus_name"));
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ADD_ = new javax.swing.JButton();
        REMOVE_ = new javax.swing.JButton();
        CLEAR_ = new javax.swing.JButton();
        SAVE_ = new javax.swing.JButton();
        CALCULATE_ = new javax.swing.JButton();
        OPEN_ = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cus_name = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        estimate_no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        sub_total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        total_tax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        net_amount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        item_qty = new javax.swing.JTextField();

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Total Tax");

        jTextField4.setText("jTextField2");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Net Amount");

        jTextField6.setText("jTextField2");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estimate");

        ADD_.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        ADD_.setText("Add");
        ADD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_ActionPerformed(evt);
            }
        });

        REMOVE_.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        REMOVE_.setText("Remove");
        REMOVE_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVE_ActionPerformed(evt);
            }
        });

        CLEAR_.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        CLEAR_.setText("Clear");
        CLEAR_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR_ActionPerformed(evt);
            }
        });

        SAVE_.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        SAVE_.setText("Save");
        SAVE_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVE_ActionPerformed(evt);
            }
        });

        CALCULATE_.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        CALCULATE_.setText("Calculate");
        CALCULATE_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULATE_ActionPerformed(evt);
            }
        });

        OPEN_.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        OPEN_.setText("Open");
        OPEN_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPEN_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OPEN_, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CALCULATE_, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVE_, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLEAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REMOVE_, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADD_, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(ADD_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(REMOVE_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CLEAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(SAVE_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CALCULATE_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(OPEN_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Customer Name");

        cus_name.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cus_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cus_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_nameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Estimate Bill No");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Date");

        try {
            date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Rate", "GST", "Total", "Quantity", "Net Sub Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.setSelectionBackground(new java.awt.Color(0, 51, 204));
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setResizable(false);
            tab.getColumnModel().getColumn(0).setPreferredWidth(350);
            tab.getColumnModel().getColumn(1).setResizable(false);
            tab.getColumnModel().getColumn(2).setResizable(false);
            tab.getColumnModel().getColumn(3).setResizable(false);
            tab.getColumnModel().getColumn(4).setResizable(false);
            tab.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Sub Total");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Total Tax");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Net Amount");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Total Item Quantity");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(estimate_no, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(item_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sub_total, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(total_tax)
                    .addComponent(net_amount))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(estimate_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(item_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cus_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_nameActionPerformed
        // TODO add your handling code here:
        if(cus_name.getSelectedItem().equals("Select")){
            JOptionPane.showMessageDialog(null, "Select A Valid Cuatomer Name");
            ADD_.setEnabled(false);
            REMOVE_.setEnabled(false);
            CLEAR_.setEnabled(false);
            SAVE_.setEnabled(false);
            CALCULATE_.setEnabled(false);
            OPEN_.setEnabled(false);
        }
        else{
            ADD_.setEnabled(true);
            REMOVE_.setEnabled(true);
            CLEAR_.setEnabled(true);
            SAVE_.setEnabled(true);
            CALCULATE_.setEnabled(true);
            OPEN_.setEnabled(true);
        }
    }//GEN-LAST:event_cus_nameActionPerformed

    private void CLEAR_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR_ActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        tab.setModel(model);
    }//GEN-LAST:event_CLEAR_ActionPerformed

    private void REMOVE_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVE_ActionPerformed
        // TODO add your handling code here:
        if(tab.getSelectedRow()==-1)
            JOptionPane.showMessageDialog(null, "No Row Selected");
        else{
            model.removeRow(tab.getSelectedRow());
            tab.setModel(model);
        }
    }//GEN-LAST:event_REMOVE_ActionPerformed

    private void CALCULATE_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULATE_ActionPerformed
        // TODO add your handling code here:
        double sub=0.00,tax=0.00,net=0.00;
        int qty=0;
        for(int i=0;i<tab.getRowCount();i++){
            sub+=Double.parseDouble(tab.getValueAt(i, 3).toString());
            tax+=Double.parseDouble(tab.getValueAt(i, 2).toString());
            net+=Double.parseDouble(tab.getValueAt(i, 5).toString());
            qty+=Double.parseDouble(tab.getValueAt(i, 4).toString());
        }
        sub_total.setText(""+sub);
        total_tax.setText(tax+"");
        net_amount.setText(""+net);
        item_qty.setText(""+qty);
    }//GEN-LAST:event_CALCULATE_ActionPerformed

    private void ADD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_ActionPerformed
        // TODO add your handling code here:
        String item_naam=JOptionPane.showInputDialog("Enter Item Name");
        String sql="select * from product where item_name='"+item_naam+"'";
            String SQL="select * from stock where item_name='"+item_naam+"'";
            try{
                pst=conn.prepareStatement(SQL);
                rs=pst.executeQuery();
                if(rs.next()){
                    if(Integer.parseInt(rs.getString("stock_available"))>0){
                        pst=conn.prepareStatement(sql);
                        rs=pst.executeQuery();
                        if(rs.next()){
                            String x=JOptionPane.showInputDialog("Enter Quantity");
                            model.addRow(new Object[]{rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),rs.getString("Total_MRP"),x,""+(Float.parseFloat(rs.getString("Total_MRP")))*Integer.parseInt(x) });
                        }
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Item Not Available");
                }
                else
                    JOptionPane.showMessageDialog(null, "No Such Item Found");
            }catch(Exception ex){
                ex.printStackTrace();
            }
            tab.setModel(model);
    }//GEN-LAST:event_ADD_ActionPerformed

    private void SAVE_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVE_ActionPerformed
        // TODO add your handling code here:
        String sql="INSERT INTO estimate(cus_name, estimate_no, date, total_qty, sub_total, total_tax, net_amount) "
                +"VALUES ('"+cus_name.getSelectedItem().toString()+"','"+estimate_no.getText()+"','"+date.getText()+"','"+item_qty.getText()
                +"','"+sub_total.getText()+"','"+total_tax.getText()+"','"+net_amount.getText()+"')";
        try{
            pst=conn.prepareStatement(sql);
            pst.execute();
            for(int i=0;i<tab.getRowCount();i++){
                String SQL="INSERT INTO estimate_contents(estimate_no, item_name, rate, GST, total, quantity, net_sub_amount) "
                        +"VALUES ('"+estimate_no.getText()+"','"+tab.getValueAt(i, 0)+"','"+tab.getValueAt(i, 1)+"','"+tab.getValueAt(i, 2)
                        +"','"+tab.getValueAt(i, 3)+"','"+tab.getValueAt(i, 4)+"','"+tab.getValueAt(i, 5)+"')";
                pst=conn.prepareStatement(SQL);
                pst.execute();
            }
            JOptionPane.showMessageDialog(null, "Estimate Saved Sucessfully");
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SAVE_ActionPerformed

    private void OPEN_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPEN_ActionPerformed
        // TODO add your handling code here:
        String x=JOptionPane.showInputDialog("Enter Estimate Bill Number");
        String sql="select * from estimate where estimate_no='"+x+"'";
        String SQL="select * from estimate_contents where estimate_no='"+x+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                cus_name.setSelectedItem((String) rs.getString("cus_name"));
                item_qty.setText(rs.getString("total_qty"));
                estimate_no.setText(rs.getString("estimate_no"));
                date.setText(rs.getString("date"));
                sub_total.setText(rs.getString("sub_total"));
                total_tax.setText(rs.getString("total_tax"));
                net_amount.setText(rs.getString("net_amount"));
                pst=conn.prepareStatement(SQL);
                rs=pst.executeQuery();
                while(rs.next()){
                    model.addRow(new Object[] {rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),rs.getString("total"),
                    rs.getString("quantity"),rs.getString("net_sub_amount")});
                }
                tab.setModel(model);
            }
            else
                JOptionPane.showMessageDialog(null, "No Such Customer Estimate Found");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_OPEN_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_;
    private javax.swing.JButton CALCULATE_;
    private javax.swing.JButton CLEAR_;
    private javax.swing.JButton OPEN_;
    private javax.swing.JButton REMOVE_;
    private javax.swing.JButton SAVE_;
    private javax.swing.JComboBox<String> cus_name;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JTextField estimate_no;
    private javax.swing.JTextField item_qty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField net_amount;
    private javax.swing.JTextField sub_total;
    private javax.swing.JTable tab;
    private javax.swing.JTextField total_tax;
    // End of variables declaration//GEN-END:variables
}
