
import java.awt.Component;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Programmer PC
 */
public class payment extends javax.swing.JPanel {

    /**
     * Creates new form payment
     */
    private PreparedStatement pst;
    private ResultSet rs;
    private ResultSet Rs;
    private final Connection conn;
    private final DefaultTableModel model;
    private final DefaultListModel mod;
    public payment() {
        initComponents();
        conn=Database.Connect();
        model=(DefaultTableModel) invoice_table.getModel();
        mod=new DefaultListModel();
        bill_list.setModel(new DefaultListModel());
        edit();
        set_value();
        generate_pay_slip_no();
    }
    private void generate_pay_slip_no(){
        pay_slip_no.setText(""+new Random().nextInt(999)+new Random().nextInt(555));
        pay_slip_no.setEditable(false);
    }
    private void edit(){
        cus_name.setEditable(false);
        date.setEditable(false);
        invoice_number.setEditable(false);
        total_amount.setEditable(false);
        total_tax.setEditable(false);
        discount.setEditable(false);
        amount.setEditable(false);
        net_amount.setEditable(false);
        balance.setEditable(false);
        amount_paid.setEditable(false);
    }
    private void set_value(){
        String sql="select * from purchase";
        try{
            pst=conn.prepareStatement(sql);
            Rs=pst.executeQuery();
            mod.removeAllElements();
            while(Rs.next()){
                mod.addElement(Rs.getString("invoice_no"));
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        bill_list.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        net_amount2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill_list = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        inv_no = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        search_cancel = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        save_and_print = new javax.swing.JButton();
        transactions = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        calculator = new javax.swing.JButton();
        open = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        invoice_number = new javax.swing.JTextField();
        cus_name = new javax.swing.JTextField();
        date = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        invoice_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        total_amount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total_tax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        net_amount = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        amount_paid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pay_mode = new javax.swing.JComboBox<>();
        pay_slip_no = new javax.swing.JTextField();

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText(" Amount");

        net_amount2.setBackground(new java.awt.Color(255, 255, 255));
        net_amount2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        net_amount2.setForeground(new java.awt.Color(0, 0, 0));
        net_amount2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        net_amount2.setText("0.00");

        setBackground(new java.awt.Color(255, 102, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payments Section");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 326, -1));

        jScrollPane1.setViewportView(bill_list);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, 261, 205));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Search Bill");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 307, -1, -1));
        jPanel1.add(inv_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 344, 231, -1));

        search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        search.setLabel("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 386, 88, 35));

        search_cancel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        search_cancel.setLabel("Cancel");
        search_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(search_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 386, 88, 35));

        refresh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 128, 44));

        save_and_print.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        save_and_print.setText("Save And Print");
        save_and_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_and_printActionPerformed(evt);
            }
        });
        jPanel1.add(save_and_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 128, 44));

        transactions.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        transactions.setText("Transactions");
        transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsActionPerformed(evt);
            }
        });
        jPanel1.add(transactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 128, 44));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 332, 10));

        calculator.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        calculator.setText("Calculator");
        calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorActionPerformed(evt);
            }
        });
        jPanel1.add(calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 128, 44));

        open.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jPanel1.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 130, 44));

        clear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 130, 44));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bill Payment");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Customer Name");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Invoice Number");

        invoice_number.setBackground(new java.awt.Color(255, 255, 255));
        invoice_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invoice_number.setForeground(new java.awt.Color(0, 0, 0));

        cus_name.setBackground(new java.awt.Color(255, 255, 255));
        cus_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cus_name.setForeground(new java.awt.Color(0, 0, 0));

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setForeground(new java.awt.Color(0, 0, 0));
        try {
            date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Date");

        invoice_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No", "Item Name", "Rate", "GST", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(invoice_table);
        if (invoice_table.getColumnModel().getColumnCount() > 0) {
            invoice_table.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Total Amount");

        total_amount.setBackground(new java.awt.Color(255, 255, 255));
        total_amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total_amount.setForeground(new java.awt.Color(0, 0, 0));
        total_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_amount.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total Tax");

        total_tax.setBackground(new java.awt.Color(255, 255, 255));
        total_tax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total_tax.setForeground(new java.awt.Color(0, 0, 0));
        total_tax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_tax.setText("0.00");
        total_tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_taxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Discount");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Net Amount");

        discount.setBackground(new java.awt.Color(255, 255, 255));
        discount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discount.setForeground(new java.awt.Color(0, 0, 0));
        discount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discount.setText("0.00");

        net_amount.setBackground(new java.awt.Color(255, 255, 255));
        net_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        net_amount.setForeground(new java.awt.Color(0, 0, 0));
        net_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        net_amount.setText("0.00");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText(" Amount");

        amount.setBackground(new java.awt.Color(102, 102, 0));
        amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 0));
        amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amount.setText("0.00");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText(" Amount Paid");

        amount_paid.setBackground(new java.awt.Color(102, 102, 0));
        amount_paid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amount_paid.setForeground(new java.awt.Color(255, 255, 0));
        amount_paid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amount_paid.setText("0.00");
        amount_paid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amount_paidMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Balance");

        balance.setBackground(new java.awt.Color(102, 102, 0));
        balance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 0));
        balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        balance.setText("0.00");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Payment Mode");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Payment Slip No.");

        pay_mode.setBackground(new java.awt.Color(255, 255, 255));
        pay_mode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pay_mode.setForeground(new java.awt.Color(0, 0, 0));
        pay_mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cash", "Card" }));

        pay_slip_no.setBackground(new java.awt.Color(255, 255, 255));
        pay_slip_no.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        pay_slip_no.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)
                        .addComponent(amount_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(pay_slip_no))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(pay_mode, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(12, 12, 12)
                                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel4))
                        .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(pay_mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13))
                    .addComponent(amount_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(pay_slip_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel14))
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void total_taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_taxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_taxActionPerformed

    private void amount_paidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amount_paidMouseClicked
        // TODO add your handling code here:
        double x=Double.parseDouble(JOptionPane.showInputDialog("Enter Amount Paid"));
        amount_paid.setText(""+x);
        balance.setText((String)""+(Double.parseDouble(amount.getText())-x));
    }//GEN-LAST:event_amount_paidMouseClicked

    private void search_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cancelActionPerformed
        // TODO add your handling code here:
        inv_no.setText(null);
    }//GEN-LAST:event_search_cancelActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        ResultSet Rs;
        String sql="select * from purchase where invoice_no='"+inv_no.getText()+"'";
        try{
            pst=conn.prepareStatement(sql);
            Rs=pst.executeQuery();
            mod.removeAllElements();
            if(Rs.next()){
                mod.addElement(Rs.getString("invoice_no"));
            }
            else
                JOptionPane.showMessageDialog(null, "Not Found");
        }catch(Exception ex){
            ex.printStackTrace();
        }
        bill_list.setModel(mod);
    }//GEN-LAST:event_searchActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        if(bill_list.getSelectedIndex()==-1)
            JOptionPane.showMessageDialog(null, "No Invoice Number Selected");
        else{
            ResultSet RS;
            String sql="select * from purchase where invoice_no='"+bill_list.getSelectedValue()+"'";
            String SQL="select * from purchase_content where invoice_no='"+bill_list.getSelectedValue()+"'";
            try{
                pst=conn.prepareStatement(sql);
                Rs=pst.executeQuery();
                if(Rs.next()){
                    cus_name.setText(Rs.getString("cus_name"));
                    date.setText(new SimpleDateFormat("dd-MM-yyyy").format(Rs.getDate("date")));
                    invoice_number.setText(Rs.getString("invoice_no"));
                    total_amount.setText(Rs.getString("total_amount"));
                    total_tax.setText(Rs.getString("total_tax"));
                    discount.setText(Rs.getString("discount"));
                    net_amount.setText(Rs.getString("net_amount")); 
                    amount.setText(Rs.getString("net_amount"));
                    pst=conn.prepareStatement(SQL);
                    RS=pst.executeQuery();
                    while(RS.next()){
                        model.addRow(new Object[] {RS.getString("sl_no"),RS.getString("item_name"),RS.getString("rate"),RS.getString("GST"),RS.getString("qty"),RS.getString("total")});
                    }
                    invoice_table.setModel(model);
                }
                else
                    JOptionPane.showMessageDialog(null, "Not Found");
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_openActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        cus_name.setText(null);
        date.setText(null);
        invoice_number.setText(null);
        total_amount.setText(null);
        discount.setText(null);
        total_tax.setText(null);
        net_amount.setText(null);
        amount.setText(null);
        amount_paid.setText(null);
        balance.setText(null);
        DefaultTableModel qwe=(DefaultTableModel) invoice_table.getModel();
        qwe.setRowCount(0);
        invoice_table.setModel(model);
        amount.setText("0.00");
        amount_paid.setText("0.00");
        balance.setText("0.00");
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        set_value();
    }//GEN-LAST:event_refreshActionPerformed

    private void calculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorActionPerformed
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_calculatorActionPerformed

    private void save_and_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_and_printActionPerformed
        // TODO add your handling code here:
        if(pay_mode.getSelectedItem().toString().equals("Select"))
            JOptionPane.showMessageDialog(null, "Select A Valid Payment Mode");
        else{
            String SQL="INSERT INTO payment(cus_name, date, invoice_no, total_amount, total_tax, discount, net_amount, "
                +"amount_paid, balance, pay_slip_no ,pay_mode, pay_date) "
                +"VALUES ('"+cus_name.getText()+"','"+date.getText()+"','"+invoice_number.getText()+"','"+total_amount.getText()+"','"
                +total_tax.getText()+"','"+discount.getText()+"','"+net_amount.getText()+"','"+amount_paid.getText()+"','"+balance.getText()
                +"','"+pay_slip_no.getText()+"','"+pay_mode.getSelectedItem().toString()+"','"+new SimpleDateFormat("yyyy-MM-dd").format(new Date())+"')";
            String s="update purchase set due='false' where invoice_no='"+invoice_number.getText()+"'";
            try{
                pst=conn.prepareStatement(SQL);
                pst.execute();
                pst=conn.prepareStatement(s);
                pst.executeUpdate();
                if(JOptionPane.showConfirmDialog(null, "Payment Slip Saved Sucessfully \n Press Yes To Print Payment Slip \n Warning: Afterwards Payment Slip Cannot Be Printed")==JOptionPane.YES_OPTION){
                    JasperDesign jd=JRXmlLoader.load(getClass().getResourceAsStream("/pay_slip.jrxml"));
                    JasperReport jp=JasperCompileManager.compileReport(jd);
                    Map mp=new HashMap();
                    mp.put("inv_no", invoice_number.getText());
                    JasperPrint jpp=JasperFillManager.fillReport(jp, mp, conn);
                    JasperViewer.viewReport(jpp, false);
                    JRViewer jr=new JRViewer(jpp);
                    Component[] comp=jr.getComponents();
                    for(Component c:comp){
                        System.out.println(c.getClass().getName());
                    }
                }
            }catch(HeadlessException | SQLException | JRException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_save_and_printActionPerformed

    private void transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsActionPerformed
        // TODO add your handling code here:
        new transactions().setVisible(true);
    }//GEN-LAST:event_transactionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount_paid;
    private javax.swing.JTextField balance;
    private javax.swing.JList<String> bill_list;
    private javax.swing.JButton calculator;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cus_name;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JTextField discount;
    private javax.swing.JTextField inv_no;
    private javax.swing.JTextField invoice_number;
    private javax.swing.JTable invoice_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField net_amount;
    private javax.swing.JTextField net_amount2;
    private javax.swing.JButton open;
    private javax.swing.JComboBox<String> pay_mode;
    private javax.swing.JTextField pay_slip_no;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save_and_print;
    private javax.swing.JButton search;
    private javax.swing.JButton search_cancel;
    private javax.swing.JTextField total_amount;
    private javax.swing.JTextField total_tax;
    private javax.swing.JButton transactions;
    // End of variables declaration//GEN-END:variables
}
