
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Programmer PC
 */
public class purchase extends javax.swing.JPanel {

    /**
     * Creates new form purchase
     */
    private PreparedStatement pst;
    private Connection conn;
    private ResultSet rs;
    private DefaultListModel md;
    private DefaultTableModel buy_mod,item_mod;
    private int i;
    private double dis;
    public purchase() {
        initComponents();
        i=1;
        dis=0.0;
        conn=Database.Connect();
        md=new DefaultListModel();
        item_list.setModel(md);
        item_mod=(DefaultTableModel) item.getModel();
        buy_mod=(DefaultTableModel) buy.getModel();
        set_date();
        set_invoice();
        item_set();
        edit();
    }
    private void edit(){
        total_amount.setEditable(false);
        total_tax.setEditable(false);
        net_amount.setEditable(false);
        discount.setEditable(false);
        remove.setEnabled(false);
        clear.setEnabled(false);
        calculate.setEnabled(false);
        generate_bill.setEnabled(false);
    }
    private void set_date(){
        date.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
        date.setEditable(false);
    }
    private void set_invoice(){
        invoice_number.setText(""+new Random().nextInt(999)+new Random().nextInt(555));
        invoice_number.setEditable(false);
    }
    private void item_set(){
        String sql="select * from product";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            md.removeAllElements();
            item_mod.setRowCount(0);
            while(rs.next()){
                md.addElement(rs.getString("item_name"));
                item_mod.addRow(new Object[] {rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),rs.getString("Total_MRP")});
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        item_list.setModel(md);
        item.setModel(item_mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        date = new javax.swing.JFormattedTextField();
        invoice_number = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        buy = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        item = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        item_list = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        i_name = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total_amount = new javax.swing.JTextField();
        total_tax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        net_amount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        generate_bill = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1368, 655));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Customer Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Date");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Invoice Number");

        cus_name.setBackground(new java.awt.Color(255, 255, 255));
        cus_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cus_name.setForeground(new java.awt.Color(0, 0, 0));

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setForeground(new java.awt.Color(0, 0, 0));
        try {
            date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        invoice_number.setBackground(new java.awt.Color(255, 255, 255));
        invoice_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invoice_number.setForeground(new java.awt.Color(0, 0, 0));

        buy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No", "Item Name", "Rate", "GST", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(buy);
        if (buy.getColumnModel().getColumnCount() > 0) {
            buy.getColumnModel().getColumn(0).setResizable(false);
            buy.getColumnModel().getColumn(1).setResizable(false);
            buy.getColumnModel().getColumn(1).setPreferredWidth(300);
            buy.getColumnModel().getColumn(2).setResizable(false);
            buy.getColumnModel().getColumn(3).setResizable(false);
            buy.getColumnModel().getColumn(4).setResizable(false);
            buy.getColumnModel().getColumn(5).setResizable(false);
        }

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Rate", "GST", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(item);
        if (item.getColumnModel().getColumnCount() > 0) {
            item.getColumnModel().getColumn(0).setResizable(false);
            item.getColumnModel().getColumn(0).setPreferredWidth(250);
            item.getColumnModel().getColumn(1).setResizable(false);
            item.getColumnModel().getColumn(2).setResizable(false);
            item.getColumnModel().getColumn(3).setResizable(false);
        }

        item_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(item_list);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Search");

        i_name.setBackground(new java.awt.Color(255, 255, 255));
        i_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_name.setForeground(new java.awt.Color(0, 0, 0));

        search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        search.setText("Go");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total Amount");

        total_amount.setBackground(new java.awt.Color(255, 255, 255));
        total_amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total_amount.setForeground(new java.awt.Color(0, 0, 0));
        total_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_amount.setText("0.00");

        total_tax.setBackground(new java.awt.Color(255, 255, 255));
        total_tax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total_tax.setForeground(new java.awt.Color(0, 0, 0));
        total_tax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_tax.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total Tax");

        discount.setBackground(new java.awt.Color(255, 255, 255));
        discount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discount.setForeground(new java.awt.Color(0, 0, 0));
        discount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discount.setText("0.00");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Discount");

        net_amount.setBackground(new java.awt.Color(255, 255, 255));
        net_amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        net_amount.setForeground(new java.awt.Color(0, 0, 0));
        net_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        net_amount.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Net Amount");

        clear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        generate_bill.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        generate_bill.setText("Generate Bill");
        generate_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_billActionPerformed(evt);
            }
        });

        calculate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(23, 23, 23)
                                .addComponent(total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)
                                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(23, 23, 23)
                                .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(generate_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(i_name, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(i_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generate_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        item_set();
    }//GEN-LAST:event_refreshActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String sql="select * from product where item_name='"+i_name.getText()+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            md.removeAllElements();
            while(rs.next()){
                md.addElement(rs.getString("item_name"));
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        item_list.setModel(md);
    }//GEN-LAST:event_searchActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        if(buy.getSelectedRow()==-1)
            JOptionPane.showMessageDialog(null, "No Row Selected");
        else{
            DefaultTableModel mdo=(DefaultTableModel) buy.getModel();
            mdo.removeRow(buy.getSelectedRow());
            buy.setModel(mdo);
        }
    }//GEN-LAST:event_removeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel) buy.getModel();
        m.setRowCount(0);
        buy.setModel(m);
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String item_naam=item_list.getSelectedValue();
        if(item_list.getSelectedIndex()!=-1) {
            String sql="select * from product where item_name='"+item_naam+"'";
            String SQL="select * from stock where item_name='"+item_naam+"'";
            try{
                pst=conn.prepareStatement(SQL);
                rs=pst.executeQuery();
                if(rs.next()){
                    if(Integer.parseInt(rs.getString("stock_available"))>0){
                        pst=conn.prepareStatement(sql);
                        rs=pst.executeQuery();
                        if(rs.next()){
                            String x=JOptionPane.showInputDialog("Enter Quantity");
                            buy_mod.addRow(new Object[]{""+i,rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),x,""+(Float.parseFloat(rs.getString("Total_MRP")))*Integer.parseInt(x) });
                            i++;
                        }
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Item Not Available");
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
            buy.setModel(buy_mod);
            remove.setEnabled(true);
            clear.setEnabled(true);
            calculate.setEnabled(true);
        } 
        else
            JOptionPane.showMessageDialog(null, "No Item Selected");
    }//GEN-LAST:event_addActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        dis=dis+Double.parseDouble(JOptionPane.showInputDialog("Enter Discount"));
        double total = 0.00,net_total = 0.00;
        float GST=(float) 0.0;
        for(int i=0;i<buy.getRowCount();i++){
            total+=Double.parseDouble(buy.getValueAt(i, 5).toString());
            GST+=Float.parseFloat(buy.getValueAt(i, 3).toString());
        }
        total_tax.setText(""+GST);
        total_amount.setText(""+total);
        discount.setText(""+dis);
        net_amount.setText(""+(total-dis));
        generate_bill.setEnabled(true);
    }//GEN-LAST:event_calculateActionPerformed

    private void generate_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_billActionPerformed
        // TODO add your handling code here:
        if(cus_name.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Enter Customer Name");
        else{
            DefaultTableModel mod=(DefaultTableModel) buy.getModel();
            String sql="INSERT INTO purchase(cus_name, date, invoice_no, total_amount, total_tax, discount, net_amount, due) "
                +"VALUES ('"+cus_name.getText()+"','"+new SimpleDateFormat("yyyy-MM-dd").format(new Date())+"','"+invoice_number.getText()+"','"+total_amount.getText()+"','"
                +total_tax.getText()+"','"+discount.getText()+"','"+net_amount.getText()+"','true')";
            try{
                pst=conn.prepareStatement(sql);
                pst.execute();
                for(int i=0;i<buy.getRowCount();i++){
                    String SQL="INSERT INTO purchase_content(sl_no, item_name, rate, GST, qty, total, invoice_no) "
                        +"VALUES ('"+mod.getValueAt(i, 0)+"','"+mod.getValueAt(i, 1)+"','"+mod.getValueAt(i, 2)+"','"+mod.getValueAt(i, 3)+"','"+
                        mod.getValueAt(i, 4)+"','"+mod.getValueAt(i, 5)+"','"+invoice_number.getText()+"')";
                    pst=conn.prepareStatement(SQL);
                    pst.execute();
                }
                JOptionPane.showMessageDialog(null, "Bill Generated Sucessfully");
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_generate_billActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTable buy;
    private javax.swing.JButton calculate;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cus_name;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JTextField discount;
    private javax.swing.JButton generate_bill;
    private javax.swing.JTextField i_name;
    private javax.swing.JTextField invoice_number;
    private javax.swing.JTable item;
    private javax.swing.JList<String> item_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField net_amount;
    private javax.swing.JButton refresh;
    private javax.swing.JButton remove;
    private javax.swing.JButton search;
    private javax.swing.JTextField total_amount;
    private javax.swing.JTextField total_tax;
    // End of variables declaration//GEN-END:variables
}
