
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Programmer PC
 */
public class voucher extends javax.swing.JPanel {

    /**
     * Creates new form voucher
     */
    private PreparedStatement pst;
    private Connection conn;
    private ResultSet rs;
    private DefaultTableModel model;
    private DefaultListModel mod;
    private boolean isNew;
    public voucher() {
        initComponents();
        conn=Database.Connect();
        mod=new DefaultListModel();
        voucher_list.setModel(new DefaultListModel());
        model=(DefaultTableModel) voucher_table.getModel();
        set_value();
        sub_total.setEditable(false);
        total_tax.setEditable(false);
        net_amount.setEditable(false);
        cus_name.setEditable(false);
        isNew=false;
        add.setEnabled(false);
        calculate.setEnabled(false);
        delete.setEnabled(false);
        save.setEnabled(false);
    }
    private void set_date(){
        date.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
        date.setEditable(false);
    }
    private void set_voucher_number(){
        voucher.setText(""+new Random().nextInt(999)+new Random().nextInt(666));
        voucher.setEditable(false);
    }
    private void set_value(){
        String sql="select * from voucher";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            mod.removeAllElements();
            while(rs.next()){
                mod.addElement(rs.getString("voucher_number"));
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        voucher_list.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voucher_no = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        new_voucher = new javax.swing.JButton();
        all_voucher = new javax.swing.JButton();
        edit_voucher = new javax.swing.JButton();
        print_voucher = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        voucher_list = new javax.swing.JList<>();
        open = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        date = new javax.swing.JFormattedTextField();
        voucher = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        voucher_table = new javax.swing.JTable();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sub_total = new javax.swing.JTextField();
        total_tax = new javax.swing.JTextField();
        net_amount = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();

        jTextField6.setText("jTextField4");

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Credit Voucher");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Enter Voucher Number");

        search.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        search.setText("Search ");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        new_voucher.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        new_voucher.setText("New Voucher");
        new_voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_voucherActionPerformed(evt);
            }
        });

        all_voucher.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        all_voucher.setText("All Vouchers");
        all_voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_voucherActionPerformed(evt);
            }
        });

        edit_voucher.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        edit_voucher.setText("Edit Voucher");
        edit_voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_voucherActionPerformed(evt);
            }
        });

        print_voucher.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        print_voucher.setText("Print Voucher");
        print_voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_voucherActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(voucher_list);

        open.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(new_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(all_voucher, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(print_voucher, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(128, 128, 128))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(voucher_no, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(23, 23, 23)
                                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(open, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(open, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voucher_no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(all_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jScrollPane1.setViewportView(jPanel2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Credit Voucher");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Date ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Voucher Number");

        try {
            date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        voucher_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No", "Item Name", "Rate", "GST", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(voucher_table);
        if (voucher_table.getColumnModel().getColumnCount() > 0) {
            voucher_table.getColumnModel().getColumn(0).setResizable(false);
            voucher_table.getColumnModel().getColumn(1).setResizable(false);
            voucher_table.getColumnModel().getColumn(1).setPreferredWidth(350);
            voucher_table.getColumnModel().getColumn(2).setResizable(false);
            voucher_table.getColumnModel().getColumn(3).setResizable(false);
            voucher_table.getColumnModel().getColumn(4).setResizable(false);
            voucher_table.getColumnModel().getColumn(5).setResizable(false);
        }

        add.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Net Amount");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sub Total");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Total Tax");

        sub_total.setBackground(new java.awt.Color(102, 102, 0));
        sub_total.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        sub_total.setForeground(new java.awt.Color(255, 255, 0));
        sub_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sub_total.setText("0.00");

        total_tax.setBackground(new java.awt.Color(102, 102, 0));
        total_tax.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        total_tax.setForeground(new java.awt.Color(255, 255, 0));
        total_tax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_tax.setText("0.00");

        net_amount.setBackground(new java.awt.Color(102, 102, 0));
        net_amount.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        net_amount.setForeground(new java.awt.Color(255, 255, 0));
        net_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        net_amount.setText("0.00");

        calculate.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        voucher_no.setText(null);
        isNew=false;
        add.setEnabled(false);
        calculate.setEnabled(false);
        delete.setEnabled(false);
        save.setEnabled(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        set_value();
        isNew=false;
        add.setEnabled(false);
        calculate.setEnabled(false);
        delete.setEnabled(false);
        save.setEnabled(false);
    }//GEN-LAST:event_refreshActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String sql="select * from voucher where voucher_number='"+voucher_no.getText()+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            mod.removeAllElements();
            if(rs.next()){
                mod.addElement(rs.getString("voucher_number"));
            }
            else
                JOptionPane.showMessageDialog(null, "No Such Voucher Found");
        }catch(Exception ex){
            ex.printStackTrace();
        }
        voucher_list.setModel(mod);
        isNew=false;
        add.setEnabled(false);
        calculate.setEnabled(false);
        delete.setEnabled(false);
        save.setEnabled(false);
    }//GEN-LAST:event_searchActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        String sql="select * from voucher where voucher_number='"+voucher_list.getSelectedValue()+"'";
        String SQL="select * from voucher_contents where voucher_number='"+voucher_list.getSelectedValue()+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            model.setRowCount(0);
            if(rs.next()){
                cus_name.setText(rs.getString("name"));
                date.setText(rs.getString("date"));
                voucher.setText(rs.getString("voucher_number"));
                sub_total.setText(rs.getString("sub_total"));
                total_tax.setText(rs.getString("total_tax"));
                net_amount.setText(rs.getString("net_amount"));
                pst=conn.prepareStatement(SQL);
                rs=pst.executeQuery();
                while(rs.next()){
                    model.addRow(new Object[] {rs.getString("sl_no"),rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),
                    rs.getString("qty"),rs.getString("total")});
                }
                voucher_table.setModel(model);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        voucher_list.setModel(mod);
        isNew=false;
        add.setEnabled(false);
        calculate.setEnabled(false);
        delete.setEnabled(false);
        save.setEnabled(false);
    }//GEN-LAST:event_openActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        double sub=0.00,tax=0.00,nett=0.00;
        for(int i=0;i<voucher_table.getRowCount();i++){
            sub+=Double.parseDouble(voucher_table.getValueAt(i, 2).toString());
            tax+=Double.parseDouble(voucher_table.getValueAt(i, 3).toString());
            nett+=Double.parseDouble(voucher_table.getValueAt(i, 5).toString());
        }
        sub_total.setText(""+sub);
        total_tax.setText(""+tax);
        net_amount.setText(""+nett);
    }//GEN-LAST:event_calculateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modd=(DefaultTableModel) voucher_table.getModel();
        modd.setRowCount(0);
        voucher_table.setModel(model);
        sub_total.setText("0.00");
        total_tax.setText("0.00");
        net_amount.setText("0.00");
        cus_name.setText(null);
        date.setText(null);
        voucher.setText(null);
        add.setEnabled(false);
        calculate.setEnabled(false);
        delete.setEnabled(false);
        save.setEnabled(false);
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if(voucher_table.getSelectedRow()==-1)
            JOptionPane.showMessageDialog(null, "No Row Selected");
        else{
            DefaultTableModel mdo=(DefaultTableModel) voucher_table.getModel();
            mdo.removeRow(voucher_table.getSelectedRow());
            voucher_table.setModel(mdo);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String item=JOptionPane.showInputDialog("Enter Item Name");
        if(item.equals(""))
            JOptionPane.showMessageDialog(null, "Enter A Valid Item");
        else{
            String sql="select * from product where item_name='"+item+"'";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    String x=JOptionPane.showInputDialog("Enter Quantity");
                    double y=Double.parseDouble(rs.getString("Total_MRP"))*Double.parseDouble(x);
                    int a;
                    try{
                        a=(Integer.parseInt(voucher_table.getValueAt(voucher_table.getRowCount()-1, 0).toString())+1);
                    }catch(Exception ex){
                        a=1;
                    }
                    model.addRow(new Object[] {""+a,
                    rs.getString("item_name"),rs.getString("rate"),rs.getString("GST"),x,y});
                }
                else
                    JOptionPane.showMessageDialog(null, "No Such Item Found");
            }catch(Exception ex){
                ex.printStackTrace();
            }
            voucher_table.setModel(model);
        }
    }//GEN-LAST:event_addActionPerformed

    private void new_voucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_voucherActionPerformed
        // TODO add your handling code here:
        cus_name.setText(null);
        cus_name.setEditable(true);
        set_date();
        set_voucher_number();
        DefaultTableModel m=(DefaultTableModel) voucher_table.getModel();
        m.setRowCount(0);
        voucher_table.setModel(model);
        sub_total.setText("0.00");
        total_tax.setText("0.00");
        net_amount.setText("0.00");
        isNew=true;
        add.setEnabled(true);
        calculate.setEnabled(true);
        delete.setEnabled(true);
        save.setEnabled(true);
    }//GEN-LAST:event_new_voucherActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(isNew==true){
            String sql="INSERT INTO voucher(name, date, voucher_number, sub_total, total_tax, net_amount) "
                +"VALUES ('"+cus_name.getText()+"','"+date.getText()+"','"+voucher.getText()+"','"+sub_total.getText()+"','"+total_tax.getText()+"','"+net_amount.getText()+"')";
            try{
                pst=conn.prepareStatement(sql);
                pst.execute();
                for(int i=0;i<voucher_table.getRowCount();i++){
                    String SQL="INSERT INTO voucher_contents(voucher_number, sl_no, item_name, rate, GST, qty, total) "
                    +"VALUES ('"+voucher.getText()+"','"+voucher_table.getValueAt(i, 0)+"','"+voucher_table.getValueAt(i, 1)+"','"
                            +voucher_table.getValueAt(i, 2)+"','"+voucher_table.getValueAt(i, 3)+"','"+voucher_table.getValueAt(i, 4)+"','"
                            +voucher_table.getValueAt(i, 5)+"')";
                    pst=conn.prepareStatement(SQL);
                    pst.execute();
                }
                JOptionPane.showMessageDialog(null, "New Voucher Added");
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Not A New Voucher");
       isNew=false;
    }//GEN-LAST:event_saveActionPerformed

    private void edit_voucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_voucherActionPerformed
        // TODO add your handling code here:
        new edit_voucher().setVisible(true);
    }//GEN-LAST:event_edit_voucherActionPerformed

    private void all_voucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_voucherActionPerformed
        // TODO add your handling code here:
        new all_vouchers().setVisible(true);
    }//GEN-LAST:event_all_voucherActionPerformed

    private void print_voucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_voucherActionPerformed
        // TODO add your handling code here:
        try {
            JasperDesign jd=JRXmlLoader.load(getClass().getResourceAsStream("/credit_voucher.jrxml"));
            JasperReport jp=JasperCompileManager.compileReport(jd);
            Map mp=new HashMap();
            mp.put("voucher",voucher.getText());
            JasperPrint jpp=JasperFillManager.fillReport(jp, mp, conn);
            JasperViewer.viewReport(jpp, false);
        } catch (JRException ex) {
            Logger.getLogger(voucher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_print_voucherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton all_voucher;
    private javax.swing.JButton calculate;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cus_name;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit_voucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField net_amount;
    private javax.swing.JButton new_voucher;
    private javax.swing.JButton open;
    private javax.swing.JButton print_voucher;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField sub_total;
    private javax.swing.JTextField total_tax;
    private javax.swing.JTextField voucher;
    private javax.swing.JList<String> voucher_list;
    private javax.swing.JTextField voucher_no;
    private javax.swing.JTable voucher_table;
    // End of variables declaration//GEN-END:variables
}
